### ISSUE TITLE
pytest support for pytest >= 3.3

### ISSUE THREAD

**Issue by ahonnecke** [rocky/pytest-trepan#1]
The pipy page seems to indicate that this package runs on 2.7 - 3.6 (under "Programming Language"):
https://pypi.org/project/pytest-trepan/

However when I attempt to install, It seems to attempt to install trepan2 and subsequently fail:
```bash
web on  ccxt-command [⇡$!?] via 🐍 3.6.4 took 4s
➜ pipenv install pytest-trepan
Installing pytest-trepan…
Looking in indexes: https://pypi.python.org/simple
Collecting pytest-trepan
  Using cached https://files.pythonhosted.org/packages/57/e8/faf22f4de258b35a71175e5e8a72c495c822def506ad555642ae72191a4e/pytest_trepan-1.0.1-py2.py3-none-any.whl
Collecting pytest>=2.6.0 (from pytest-trepan)
  Using cached https://files.pythonhosted.org/packages/77/64/3a76f6fbb0f392d60c5960f2b2fbad8c2b802dada87ca6d1b99c0083a929/pytest-3.6.3-py2.py3-none-any.whl
Collecting trepan2>=0.7.6 (from pytest-trepan)
  Using cached https://files.pythonhosted.org/packages/1f/4b/105fb787e9fe8319568c1c73f690514a71414929a827772a2c740065dcf3/trepan2-0.8.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/95/8fsl_k5140d7mysbx4q8041r0000gq/T/pip-install-4kyb0xuu/trepan2/setup.py", line 18, in <module>
        raise Exception(mess)
    Exception: Only Python Versions 2.4 to 2.7 are supported in this package.
    For your Python, version 3.6, see trepan3k

    ----------------------------------------

Error:  An error occurred while installing pytest-trepan!
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/95/8fsl_k5140d7mysbx4q8041r0000gq/T/pip-install-4kyb0xuu/trepan2/


web on  ccxt-command [⇡$!?] via 🐍 3.6.4 took 2s
➜ pipenv run python --version
Python 3.6.4
```

Perhaps I'm misunderstanding, what should I be installing to get trepan3k to work in pytest?

**Comment by rocky** [comment]
If I remember correctly betweekn pytest 3.2 and 3.3 there was a change in pytest that broke this. 

I asked about this on the IRC pytest suggest but didn't get an answer in the couple of days I as on. (In fact, that channel seems to be mostly dead.)

So a workaround is to use something like pytest 3.2. 

It would be great if someone would spend the time to see how to fix. I'm probably not going to be able to do that in the near future, but if someone else is willing to work on it, I'm happy to answer any questions.

**Comment by ahonnecke** [comment]
I'm happy to work on it, but I'd probably need a fair bit of direction.  Do you have any suggestions as to where I could start? @rocky

**Comment by rocky** [comment]
Here are some possibilities. Verify what I wrote - it breaks around 3.2, 3.3 - I'm going from memory. From the release notes see what needs to be changed. I recall/suspect things got simpler.

Or possibly ignore that and just work from scratch without any baggage.  Figure out from the pytest docs what you are supposed to do to be able to capture input and output and write a sample plugin that does that. With this, I bet your plugin can easily be adapted to work with trepan3k which is far more flexible than pdb. 

If you can get it working on some code of your choosing it might be as simple as adding `from trepan.api import debug; debug()`
